# Generated by Django 3.2.9 on 2021-11-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='i_cat', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_item', to='main.item', verbose_name='Название'),
        ),
    ]
